POST http://localhost:3005/api/orders
Content-Type: application/json 

{       
    "id": "345",
    "orderNumber": 34,
    "responsiblePerson": "Nina Weiler",
    "healthCareDistrict": "TAYS",
    "vaccine": "Phiezer",
    "injections": 6,
    "arrived": "2021-04-07T01:10:30.696768Z"
}
###

GET http://localhost:3005/api/orders

###
GET http://localhost:3005/api/orders/60ce36e223842d26b01799d5
